// jest.config.js
const nextJest = require('next/jest')

const createJestConfig = nextJest({
  dir: "./",
})

const customJestConfig = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
    "^@components/(.*)$": "<rootDir>/src/components/$1",
    "^@hooks/(.*)$": "<rootDir>/src/hooks/$1",
    "^@utils/(.*)$": "<rootDir>/src/utils/$1",
    "^@lib/(.*)$": "<rootDir>/src/lib/$1",
  },

  // Explicitly define where tests are located
  testMatch: [
    "<rootDir>/src/**/__tests__/**/*.[jt]s?(x)",
    "<rootDir>/src/**/*.(test|spec).[jt]s?(x)",
    "<rootDir>/tests/**/*.(test|spec).[jt]s?(x)"
  ],

  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
  },

  reporters: [
    "default", // Default reporter
    "jest-summary-reporter" // Add the summary reporter
  ],

  testEnvironment: "jest-environment-jsdom",
  moduleFileExtensions: ["js", "jsx", "json"],
  // Cache configuration for faster testing
  cache: true,
  cacheDirectory: ".next/cache/jest",
  // Performance optimizations
  maxWorkers: "50%",
  collectCoverageFrom: ["src/**/*.{js,jsx}", "!src/**/*.test.{js,jsx}", "!src/**/*.spec.{js,jsx}"],
  // Prevent Haste module name collisions with the standalone production bundle generated by Next.js
  modulePathIgnorePatterns: ["<rootDir>/.next/standalone"],
}

module.exports = createJestConfig(customJestConfig)