services:
  # -----------------------------
  # Backend API Service
  # -----------------------------
  backend:
    container_name: cedo-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5000:5000"
    # If you have an external database, uncomment and configure these
    # depends_on:
    #   - mongo
    #   - mysql

  # -----------------------------
  # Frontend (Next.js) Service
  # -----------------------------
  frontend:
    container_name: cedo-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend

# Example external database services (optional)
# services:
#   mongo:
#     image: mongo:7.0
#     restart: unless-stopped
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
#       - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
#     volumes:
#       - mongo-data:/data/db
#     ports:
#       - "27017:27017"
#
#   mysql:
#     image: mysql:8.3
#     restart: unless-stopped
#     environment:
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#       - MYSQL_DATABASE=${MYSQL_DATABASE}
#       - MYSQL_USER=${MYSQL_USER}
#       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#     volumes:
#       - mysql-data:/var/lib/mysql
#     ports:
#       - "3306:3306"
#
# volumes:
#   mongo-data:
#   mysql-data: 