services:
  - type: web
    name: cedo-backend
    env: node
    rootDir: backend
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://cedo-event-proposal-ms.onrender.com

  - type: web
    name: cedo-frontend
    env: node
    rootDir: frontend
    plan: free
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://ceproposal-ms.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://ceproposal-ms.onrender.com/api
      - key: BACKEND_URL
        value: https://ceproposal-ms.onrender.com
      - key: API_URL
        value: https://ceproposal-ms.onrender.com/api
